### PR TITLE
a pr that will never be acknowledged to time

### PR DESCRIPTION
**Pull request by skepfusky**
## changes
- set some absolute paths on `tsconfig.json` so you don't have to write `../../../../utils/something.ts` again, plus it looks clean and readable.
- "fuck mac users"? dude, language!
- some weird capitalization on readme and on the client too.
- setting `strict` to `true` to enforce type-checking and setting it to false probably defeats the purpose of using typescript in the first place. if you wish, you can put it back to `false`.

## suggestions
- nothing.

### CODE REVIEW

**Comment by skepfusky** [comment]
god fucking damn it.

**Comment by skepfusky** [comment]
Fuck, I knew you didn't need me. "Contributing to open source is fun" they said, "it'll be fun they said". Oh well... I tried to improve on this project, I saw that fork on another repo and you never acknowledged this PR. I just fucking knew you didn't need me at all.

**Comment by skepfusky** [comment]
Guess you can't delete PRs anyways, I'm not good for this industry anyways.

**Comment by skepfusky** [comment]
damn it, a merge conflict.

**Comment by skepfusky** [comment]
Oh well @VulpoTheDev, it's your call.

**Comment by VulpoTheDev** [comment]
Heya skep, sorry for that, I never received a GitHub Notification or Email regarding this PR, i'll look into it right now

**Comment by VulpoTheDev** [comment]
Heya Skep, it's not letting me fix these errors, not sure if it relates to the repository not existing or something else

**Comment by skepfusky** [comment]
@VulpoTheDev Oh I removed the repo out of frustration, my bad lol -- I'll retry my previous changes since you pushed new changes that causes a conflict

**Comment by VulpoTheDev** [comment]
Okie also if possible could you re-add me on discord as well

**Pull request closed without merging**
